import type { Recipe, RecipeIngredient, RecipeStep, PrepAction } from "../types/schema";

/**
 * Migrated from v1's `RECIPES` const in web/index.html. v1 only ever
 * recorded a handful of ingredients as free-text quantities ("3 cups",
 * "a thumbnail piece") and never ingredient-level nutrition. Converting
 * those to grams/ml/pieces is itself an estimate on top of the ingredient
 * nutrition estimate — RecipeIngredient.estimated marks that conversion
 * specifically: false where v1 already gave an exact gram/ml/piece count,
 * true where I converted a cup/tbsp/tsp/handful/pinch figure.
 *
 * All 16 keep status "draft" and source.kind "own" per spec section 7,
 * whether or not a given line is estimated — none of them has gone
 * through the "Tulika confirmed quantities" verification pass yet.
 */

function ri(ingredientId: string, qty: number, estimated: boolean, note?: string): RecipeIngredient {
  return note ? { ingredientId, qty, estimated, note } : { ingredientId, qty, estimated };
}

function step(id: string, text: string, minutes?: number): RecipeStep {
  return minutes != null ? { id, text, minutes } : { id, text };
}

function prep(kind: PrepAction["kind"], leadHours: number, text: string): PrepAction {
  return { kind, leadHours, text };
}

export const RECIPES: Recipe[] = [
  {
    id: "idli",
    familyId: "fermented-batter",
    name: "Fermented idli batter",
    axisValues: { form: "steamed", "add-ins": "none" },
    yieldServings: 2,
    ingredients: [
      ri("idli-rice", 600, true, "3 cups"),
      ri("urad-dal", 200, true, "1 cup"),
      ri("poha", 25, true, "1/2 cup, thick poha"),
      ri("salt", 12, true, "2 tsp"),
      ri("fenugreek-seeds", 4, true, "1 tsp"),
    ],
    steps: [
      step("s1", "Soak the rice and poha in one bowl, the urad dal and fenugreek in another, for 5 hours.", 10),
      step("s2", "Grind the urad dal first with cold water until light and airy. Then grind the rice to a slightly coarse paste.", 20),
      step("s3", "Combine, add salt, mix with your hand. Leave covered at room temperature overnight."),
      step("s4", "Steam in lots of 6. Twelve minutes, then rest 2 minutes before unmoulding.", 15),
    ],
    prepActions: [
      prep("soak", 14, "Soak idli rice, urad dal and poha, 5 hours — start Saturday evening."),
      prep("ferment", 10, "Grind and leave the batter out overnight."),
    ],
    shelfLifeDays: 5,
    freezable: false,
    slots: ["breakfast"],
    activeMinutes: 30,
    source: { kind: "own" },
    status: "draft",
  },
  {
    id: "chutney",
    familyId: null,
    name: "Peanut chutney",
    axisValues: {},
    yieldServings: 2,
    ingredients: [
      ri("roasted-peanuts", 150, true, "1 cup"),
      ri("dried-red-chilli", 3, false),
      ri("garlic", 4, false, "4 cloves"),
      ri("tamarind", 5, true, "thumbnail piece"),
      ri("mustard-seeds", 2, true, "1/2 tsp"),
      ri("curry-leaves", 3, true, "1 sprig"),
      ri("oil", 5, true, "1 tsp"),
    ],
    steps: [
      step("s1", "Grind peanuts, chillies, garlic, tamarind and salt with enough water for a thick paste.", 10),
      step("s2", "Temper mustard seeds, curry leaves and a pinch of hing in the oil, pour over.", 5),
    ],
    prepActions: [],
    shelfLifeDays: 4,
    freezable: false,
    slots: ["side"],
    activeMinutes: 15,
    source: { kind: "own" },
    status: "draft",
  },
  {
    id: "rajma",
    familyId: "legume-curry",
    name: "Rajma",
    axisValues: { legume: "rajma", souring: "tomato", tempering: "onion", finish: "garam masala" },
    yieldServings: 2,
    ingredients: [
      ri("rajma", 400, true, "2 cups, soaked overnight"),
      ri("onion", 3, false, "3, finely chopped"),
      ri("tomato", 4, false, "4, pureed"),
      ri("ginger-garlic-paste", 30, true, "2 tbsp"),
      ri("oil", 30, true, "2 tbsp"),
      ri("turmeric", 2, true, "1 tsp"),
      ri("coriander-powder", 4, true, "2 tsp"),
      ri("red-chilli-powder", 3, true, "1.5 tsp"),
      ri("garam-masala", 2, true, "1 tsp"),
      ri("rajma-masala", 4, true, "2 tsp"),
    ],
    steps: [
      step("s1", "Pressure cook the soaked rajma with salt, 6 whistles. Keep the cooking water.", 25),
      step("s2", "Brown the onions properly in the oil. Pale onions make flat rajma.", 10),
      step("s3", "Add ginger garlic paste, then the tomato puree and dry spices. Cook until the oil separates.", 10),
      step("s4", "Add the rajma with its water. Simmer 20 minutes, mashing a ladleful against the side to thicken.", 20),
    ],
    prepActions: [prep("soak", 12, "Soak the rajma, at least 8 hours before cooking.")],
    shelfLifeDays: 4,
    freezable: true,
    slots: ["lunch", "dinner"],
    activeMinutes: 25,
    source: { kind: "own" },
    status: "draft",
  },
  {
    id: "chana",
    familyId: "legume-curry",
    name: "Chana masala",
    axisValues: { legume: "kabuli chana", souring: "amchur", tempering: "onion", finish: "amchur" },
    yieldServings: 2,
    ingredients: [
      ri("kabuli-chana", 400, true, "2 cups, soaked overnight"),
      ri("onion", 3, false, "3, finely chopped"),
      ri("tomato", 4, false, "4, pureed"),
      ri("ginger-garlic-paste", 30, true, "2 tbsp"),
      ri("oil", 30, true, "2 tbsp"),
      ri("chana-masala-spice", 4, true, "2 tsp"),
      ri("amchur", 2, true, "1 tsp"),
      ri("black-tea-bag", 1, false),
    ],
    steps: [
      step("s1", "Pressure cook the chana with salt and the tea bag, 6 whistles. Remove the bag.", 25),
      step("s2", "Same onion tomato base as the rajma.", 15),
      step("s3", "Add the chana with a cup of its water, simmer 15 minutes, finish with amchur.", 15),
    ],
    prepActions: [prep("soak", 12, "Soak the kabuli chana, at least 8 hours before cooking.")],
    shelfLifeDays: 4,
    freezable: false,
    slots: ["lunch", "dinner"],
    activeMinutes: 25,
    source: { kind: "own" },
    status: "draft",
  },
  {
    id: "dal",
    familyId: "legume-curry",
    name: "Dal tadka",
    axisValues: { legume: "toor dal", souring: "lemon", tempering: "cumin-garlic-ghee", finish: "lemon" },
    yieldServings: 2,
    ingredients: [
      ri("toor-dal", 300, true, "1.5 cups"),
      ri("turmeric", 2, true, "1 tsp"),
      ri("ghee", 20, true, "1.5 tbsp"),
      ri("cumin-seeds", 2, true, "1 tsp"),
      ri("garlic", 8, false, "8 cloves, sliced"),
      ri("dried-red-chilli", 2, false),
      ri("tomato", 1, false, "1, chopped"),
      ri("lemon", 0.5, false, "half"),
    ],
    steps: [
      step("s1", "Pressure cook the dal with turmeric and salt, 3 whistles. Whisk smooth.", 15),
      step("s2", "Heat the ghee, add cumin, then garlic until golden, then chilli, hing and tomato.", 8),
      step("s3", "Pour over the dal, simmer 5 minutes, finish with lemon.", 5),
    ],
    prepActions: [],
    shelfLifeDays: 3,
    freezable: false,
    slots: ["lunch"],
    activeMinutes: 20,
    source: { kind: "own" },
    status: "draft",
  },
  {
    id: "rolls",
    familyId: "rolls",
    name: "Air fried rice paper chicken rolls",
    axisValues: { wrapper: "rice paper", filling: "chicken mince", "cook method": "air fried" },
    yieldServings: 2,
    ingredients: [
      ri("chicken-mince", 400, false),
      ri("rice-paper", 16, false),
      ri("spring-onion", 4, false, "4, chopped"),
      ri("carrot", 1, false, "1, grated"),
      ri("garlic", 4, false, "4 cloves"),
      ri("ginger", 10, true, "1 inch"),
      ri("soy-sauce", 30, true, "2 tbsp"),
      ri("sesame-oil", 10, true, "2 tsp"),
      ri("black-pepper", 2, true, "1 tsp"),
    ],
    steps: [
      step("s1", "Cook the mince with garlic, ginger, spring onion and carrot until completely dry. Wet filling tears the wrapper.", 15),
      step("s2", "Add soy, sesame oil and pepper. Cool fully.", 10),
      step("s3", "Dip each sheet 8 seconds, fill, fold the sides in, roll tight.", 15),
      step("s4", "Spray with oil, air fry 180C for 10 minutes, turning once.", 10),
    ],
    prepActions: [],
    shelfLifeDays: 2,
    freezable: false,
    slots: ["dinner"],
    activeMinutes: 40,
    source: { kind: "own" },
    status: "draft",
  },
  {
    id: "fish",
    familyId: null,
    name: "Air fried fish with greens",
    axisValues: {},
    yieldServings: 2,
    ingredients: [
      ri("fish-surmai-basa", 400, false),
      ri("lemon", 1, false),
      ri("ginger-garlic-paste", 15, true, "1 tbsp"),
      ri("turmeric", 1, true, "1/2 tsp"),
      ri("red-chilli-powder", 2, true, "1 tsp"),
      ri("oil", 10, true, "2 tsp"),
      ri("spinach", 300, false, "or beans"),
      ri("garlic", 3, false, "3 cloves"),
    ],
    steps: [
      step("s1", "Marinate the fish in everything except the greens. Refrigerate."),
      step("s2", "Air fry 180C for 12 minutes.", 12),
      step("s3", "Greens: garlic in half a teaspoon of oil, then the greens, 3 minutes, salt and pepper.", 5),
    ],
    prepActions: [prep("marinate", 48, "Marinate the fish, into the fridge.")],
    shelfLifeDays: 2,
    freezable: false,
    slots: ["dinner"],
    activeMinutes: 15,
    source: { kind: "own" },
    status: "draft",
  },
  {
    id: "oats",
    familyId: null,
    name: "Overnight oats",
    axisValues: {},
    yieldServings: 2,
    ingredients: [
      ri("rolled-oats", 80, false),
      ri("greek-yogurt", 200, false),
      ri("milk", 200, false),
      ri("chia-seeds", 20, true, "2 tbsp"),
      ri("banana", 1, false),
      ri("cinnamon", 1, true, "1/2 tsp"),
    ],
    steps: [
      step("s1", "Layer everything into two jars. Stir once so the chia does not clump at the bottom.", 5),
      step("s2", "Refrigerate. Good for 3 days."),
    ],
    prepActions: [prep("other", 8, "Layer into jars, refrigerate overnight.")],
    shelfLifeDays: 3,
    freezable: false,
    slots: ["breakfast"],
    activeMinutes: 5,
    source: { kind: "own" },
    status: "draft",
  },
  {
    id: "smoothie",
    familyId: null,
    name: "Smoothie freezer pack",
    axisValues: {},
    yieldServings: 2,
    ingredients: [
      ri("banana", 1, false, "in chunks"),
      ri("spinach", 60, true, "2 handfuls"),
      ri("peanut-butter", 32, true, "2 tbsp"),
      ri("milk", 400, false),
      ri("greek-yogurt", 100, false),
    ],
    steps: [
      step("s1", "Freeze the banana, spinach and peanut butter in a bag.", 10),
      step("s2", "Tip into the blender with milk and yogurt. Ninety seconds.", 2),
    ],
    prepActions: [prep("other", 60, "Bag and freeze Sunday night for Tuesday morning.")],
    shelfLifeDays: 7,
    freezable: true,
    slots: ["breakfast"],
    activeMinutes: 10,
    source: { kind: "own" },
    status: "draft",
  },
  {
    id: "chilla",
    familyId: null,
    name: "Besan chilla",
    axisValues: {},
    yieldServings: 2,
    ingredients: [
      ri("besan", 200, false),
      ri("onion", 1, false, "1, fine"),
      ri("tomato", 1, false, "1, fine"),
      ri("green-chilli", 2, false),
      ri("coriander-leaves", 10, true, "handful"),
      ri("ajwain", 1, true, "1/2 tsp"),
      ri("oil", 10, true, "2 tsp"),
    ],
    steps: [
      step("s1", "Whisk besan and water to a thin pouring batter. Rest 10 minutes.", 10),
      step("s2", "Stir in the vegetables and ajwain. Salt it only when you are about to cook."),
      step("s3", "One ladle per chilla on a hot non-stick tawa, half a teaspoon of oil, 2 minutes a side.", 10),
    ],
    prepActions: [prep("other", 10, "Whisk the batter, no salt yet, the night before.")],
    shelfLifeDays: 1,
    freezable: false,
    slots: ["breakfast"],
    activeMinutes: 20,
    source: { kind: "own" },
    status: "draft",
  },
  {
    id: "uttapam",
    familyId: "fermented-batter",
    name: "Uttapam",
    axisValues: { form: "pan-cooked", "add-ins": "onion-tomato-chilli" },
    yieldServings: 2,
    ingredients: [
      // Deliberately excludes the batter itself — it's the leftover of the
      // Friday idli batch, already in that week's shopping list via idli's
      // own ingredients. Including a separate batter-equivalent quantity
      // here would double count it. See checkpoint notes: this does mean
      // uttapam's own derived nutrition only covers the fresh toppings.
      ri("onion", 1, false, "1, fine"),
      ri("tomato", 1, false, "1, fine"),
      ri("green-chilli", 2, false),
      ri("coriander-leaves", 10, true, "handful"),
      ri("oil", 10, true, "2 tsp"),
    ],
    steps: [
      step("s1", "Thick ladle of batter on a medium tawa. Do not spread it thin.", 3),
      step("s2", "Scatter the toppings on the wet surface and press them in.", 2),
      step("s3", "Cover, cook 3 minutes, flip, 2 minutes uncovered.", 5),
    ],
    prepActions: [],
    shelfLifeDays: 0,
    freezable: false,
    slots: ["dinner"],
    activeMinutes: 10,
    source: { kind: "own" },
    status: "draft",
  },
  {
    id: "raita",
    familyId: null,
    name: "Carrot cucumber raita",
    axisValues: {},
    yieldServings: 2,
    ingredients: [
      ri("curd", 300, false),
      ri("cucumber", 1, false, "1, grated"),
      ri("carrot", 1, false, "1, grated"),
      ri("roasted-jeera-powder", 1, true, "1/2 tsp"),
      ri("black-salt", 1, true, "pinch"),
    ],
    steps: [
      step("s1", "Squeeze the grated cucumber dry. Skipping this is why raita turns watery.", 5),
      step("s2", "Whisk the curd smooth, fold everything in.", 5),
    ],
    prepActions: [prep("other", 14, "Made the night before, into the lunch box.")],
    shelfLifeDays: 1,
    freezable: false,
    slots: ["side"],
    activeMinutes: 10,
    source: { kind: "own" },
    status: "draft",
  },
  {
    id: "soup",
    familyId: null,
    name: "Moong dal soup",
    axisValues: {},
    yieldServings: 2,
    ingredients: [
      ri("moong-dal", 200, true, "1 cup"),
      ri("garlic", 8, false, "8 cloves"),
      ri("turmeric", 1, true, "1/2 tsp"),
      ri("black-pepper", 2, true, "1 tsp"),
      ri("lemon", 1, false),
    ],
    steps: [
      step("s1", "Pressure cook the dal with turmeric and garlic, 3 whistles.", 15),
      step("s2", "Blend completely smooth, thin with hot water to a drinkable consistency.", 5),
      step("s3", "Black pepper, salt, lemon at the end. No tempering.", 2),
    ],
    prepActions: [prep("other", 14, "Pressure cook and blend the base the night before.")],
    shelfLifeDays: 1,
    freezable: false,
    slots: ["dinner"],
    activeMinutes: 15,
    source: { kind: "own" },
    status: "draft",
  },
  {
    id: "naatukodi",
    familyId: "chicken-curry",
    name: "Naatukodi curry",
    axisValues: { cut: "country chicken bone-in", fat: "oil", souring: "tomato", base: "onion-tomato masala", "add-in": "none" },
    yieldServings: 2,
    ingredients: [ri("country-chicken", 1000, true, "1 kg — real quantities and yield not yet supplied, see spec section 10")],
    steps: [step("s1", "Cooked to your own method.")],
    prepActions: [],
    shelfLifeDays: 2,
    freezable: false,
    slots: ["lunch", "dinner"],
    activeMinutes: 45,
    source: { kind: "own" },
    status: "draft",
  },
  {
    id: "nechicken",
    familyId: "chicken-curry",
    name: "North Eastern chicken curry with potatoes",
    axisValues: { cut: "broiler bone-in", fat: "oil", souring: "none", base: "ginger-garlic-chilli paste", "add-in": "potato" },
    yieldServings: 2,
    ingredients: [
      ri("chicken-curry-cut", 800, true, "800 g — real quantities and yield not yet supplied, see spec section 10"),
      ri("potato", 3, true, "3 — real quantities and yield not yet supplied"),
    ],
    steps: [step("s1", "Cooked to your own method.")],
    prepActions: [],
    shelfLifeDays: 2,
    freezable: false,
    slots: ["dinner", "lunch"],
    activeMinutes: 40,
    source: { kind: "own" },
    status: "draft",
  },
  {
    id: "turkish",
    familyId: "eggs",
    name: "Turkish eggs",
    axisValues: { method: "poached", base: "garlic yogurt" },
    yieldServings: 2,
    ingredients: [
      ri("greek-yogurt", 150, true, "150 g — real quantities not yet supplied, see spec section 10"),
      ri("eggs", 4, true, "4 — real quantities not yet supplied"),
    ],
    steps: [step("s1", "Cooked to your own method.")],
    prepActions: [],
    shelfLifeDays: 0,
    freezable: false,
    slots: ["breakfast"],
    activeMinutes: 15,
    source: { kind: "own" },
    status: "draft",
  },
];

export const RECIPES_BY_ID: Record<string, Recipe> = Object.fromEntries(RECIPES.map((r) => [r.id, r]));
